sonar.organization=ver1812
sonar.projectKey=ver1812_vighnesh_frontend
sonar.projectName=vighnesh_frontend

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/coverage/**

sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info
